#!/bin/bash

USAGE="environment"
TOOLSDIR="${APITOOLS_HOME}"

. "$TOOLSDIR/config/global"
. "$TOOLSDIR/lib/functions"
. "$TOOLSDIR/lib/nintestfunctions"

testName:="$(basename $0)"
if [ "$OUTFile" = "" ] ; then
	OUTFile="${testName}.1.out"
	echo > $OUTFile
fi

parseCommandline "$@"
checkArgs 1
loadTestParams "${ARGS[0]}"
echo -e "\n\tNow Testing: $testName; OPTS=${OPTS[@]}; ARGS=${ARGS[@]}; OUTFile=$OUTFile; \n\t\ttestParams=$testParams" 2>&1 | tee -a $OUTFile

# re-parse using test Parameters
parseCommandline ${OPTS[@]} $testParams

loadConfig "${ARGS[0]}"
loadTestConfig 

# NTest <nameofcall(s)> ${OPTS[@]} $environment
NTest import ${OPTS[@]} $host_alias $api 2>&1 | tee -a $OUTFile #[zip_file] 
NTest importAll ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile #[directory] 
NTest importBundle ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile #zip_file 
NTest importDeploy ${OPTS[@]} $environment $api_name 2>&1 | tee -a $OUTFile

echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
echo -e "		End of Testing $testName" 2>&1 | tee -a $OUTFile
echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
