#!/bin/bash

NTest() {
	echo -e "TESTing: $@: $*\n\n\n\n" >>$OUTFile
	$@
}

loadTestConfig() {
	environment="${ARGS[0]}"
	host_alias="${ARGS[1]}"
	apiproxy="${ARGS[2]}"
	api_name="${ARGS[2]}"
	apiproduct="${ARGS[3]}"
	apiproduct_name="${ARGS[3]}"
	app_name="${ARGS[4]}"
	revision="${ARGS[5]}"
	cache_name="${ARGS[6]}"
	consumer_key="${ARGS[7]}"
	keystore_name="${ARGS[8]}"
	server_uuid="${ARGS[9]}"
	virtual_host_name="${ARGS[10]}"
}