#!/bin/bash

[[ -f "${HOME}/apigee/../README.md" ]] && export APITOOLS_HOME="${HOME}/apigee"

export DEBUG=0
chmod 600 $HOME/.curlrc
echo -n "" >$HOME/.curlrc
export FRMT="json"

if [ ${APITOOLS_HOME} ] ; then

	# export HOST_ALIAS="${ORGANIZATION}-${ENVIRONMENT}"; export PORT=":8080"

	export ORGANIZATION="advana"
	export ENVIRONMENT="dev"
	export DEVELOPER="devops@540.co"
	export SCHEME="https"
	export HOST_ALIAS="api.apigee"
	export DOMAIN=".advana.540.co"
	export PORT=""

else
	echo "NO APITOOLS_HOME Directory: [${APITOOLS_HOME}]"
	exit 1
fi

export TOOLSDIR="${APITOOLS_HOME}"
export APISDIR="${HOME}/Projects/advana/${ORGANIZATION}/${ENVIRONMENT}/apis"
export APIGEE_HOST="${SCHEME}://${HOST_ALIAS}${DOMAIN}${PORT}/v1"
export ORG=${ORGANIZATION}
export ENV=${ENVIRONMENT}
export PATH="${PATH}:${APITOOLS_HOME}/bin"
export CDPATH="${CDPATH}:${APISDIR}/.."
export MOST="${APIGEE_HOST}"

source $HOME/.aliases

echo "APITOOLS ${APITOOLS_HOME} is set @ `ls -l ~/apigee` for ${ORGANIZATION}:${ENVIRONMENT}"
