#!/bin/bash

export APITOOLS_HOME="$HOME/apigee"

export DEBUG=0
chmod 600 $HOME/.curlrc
echo -n "" >$HOME/.curlrc

export ORGANIZATION="diuptt-dev"
export ORG=$ORGANIZATION

if [ -d $APITOOLS_HOME ] ; then
	export PATH="$PATH:$APITOOLS_HOME/bin"
	export TOOLSDIR="${APITOOLS_HOME}"
	export APISDIR="$HOME/$ORG/apis"
	export CDPATH="$CDPATH:$APISDIR"
	export FRMT="json"
	export ENVIRONMENT="api-dev"
	export ENV=$ENVIRONMENT
	export DEVELOPER="diupttapigadm@gmail.com"

	#export HOST_ALIAS="$ORGANIZATION-$ENVIRONMENT"
	export HOST_ALIAS="35.192.43.243"
	#export HOST_ALIAS="api-dev.api"
	export DOMAIN="diuptt.io"
	export PORT="8080"
	#export APIGEE_HOST="${HOST_ALIAS}.${DOMAIN}:${PORT}"
	export APIGEE_HOST="${HOST_ALIAS}:${PORT}/v1"
	export MOST="http://${APIGEE_HOST}"

	export ae_org=$ORGANIZATION
	export ae_password="Apigee\\!234"
	export ae_username="terry.david@540.co"

else
	echo "NO [$APITOOLS_HOME] Directory"
fi

source $HOME/.aliases
