#!/bin/bash

[[ -f "${HOME}/apigee/../README.md" ]] && export APITOOLS_HOME="${HOME}/apigee"

export DEBUG=0
chmod 600 $HOME/.curlrc
echo -n "" >$HOME/.curlrc
export FRMT="json"

if [ ${APITOOLS_HOME} ] ; then

	export ORGANIZATION="lite"
	export ENVIRONMENT="stage"
	export DEVELOPER="terry.david@540.co"
	export SCHEME="https"
	export HOST_ALIAS="mgmt-api.prod"
	#export HOST_ALIAS="${ORGANIZATION}-${ENVIRONMENT}"; export PORT=":8080"
	export DOMAIN=".lite-portal.com"
	export PORT=""

else
	echo "NO APITOOLS_HOME Directory: [${APITOOLS_HOME}]"
	exit 1
fi

export TOOLSDIR="${APITOOLS_HOME}"
export APISDIR="${HOME}/Projects/rso/${ORGANIZATION}/${ENVIRONMENT}/apis"
if [[ ! -d $APISDIR ]] ; then
    if [[ ! -d ${HOME}/Projects/rso/${ORGANIZATION}/${ENVIRONMENT} ]] ; then
        if [[ ! -d ${HOME}/Projects/rso/${ORGANIZATION} ]] ; then
            mkdir ${HOME}/Projects/rso/${ORGANIZATION}
        fi
        mkdir ${HOME}/Projects/rso/${ORGANIZATION}/${ENVIRONMENT}
    fi
    mkdir ${APISDIR}
fi


export APIGEE_HOST="${SCHEME}://${HOST_ALIAS}${DOMAIN}${PORT}/v1"
export ORG=${ORGANIZATION}
export ENV=${ENVIRONMENT}
export PATH="${PATH}:${APITOOLS_HOME}/bin"
export CDPATH="${CDPATH}:${APISDIR}"
export MOST="${APIGEE_HOST}"

source $HOME/.aliases

echo -en "APITOOLS ${APITOOLS_HOME} is set @\n\t${APISDIR}\n"
