#!/bin/bash

TOOLSDIR="${APITOOLS_HOME}"
APISDIR="$HOME/git/guardian/apis"
ORGANIZATION="glic"
DEVELOPER="ServiceNet_Support@glic.com"

# default Data format for input & output: json OR xml
FRMT="xml"

DEBUG="false"
echo -n "" >$HOME/.curlrc

