#!/bin/bash

TOOLSDIR="${APITOOLS_HOME}"
APISDIR="$HOME/apigee/apis"
ORGANIZATION="tdavidapigeecom"
DEVELOPER="tdavid@apigee.com"

# default Data format for input & output: json OR xml
FRMT="xml"

DEBUG="false"
echo -n "" >$HOME/.curlrc

