#!/bin/bash

USAGE="environment"
TOOLSDIR="${APITOOLS_HOME}"

. "$TOOLSDIR/config/global"
. "$TOOLSDIR/lib/functions"
. "$TOOLSDIR/lib/nintestfunctions"

testName="$(basename $0)"
if [ "$OUTFile" = "" ] ; then
	OUTFile="${testName}.1.out"
	echo > $OUTFile
fi

parseCommandline "$@"
checkArgs 1
loadTestParams "${ARGS[0]}"
echo -e "\tNow Testing: $testName; OPTS=${OPTS[@]}; ARGS=${ARGS[@]}; OUTFile=$OUTFile; \n\t\ttestParams=$testParams" | tee -a $OUTFile

# re-parse using test Parameters
parseCommandline ${OPTS[@]} $testParams

loadConfig "${ARGS[0]}"
loadTestConfig 

#NTest <nameofcall(s)> ${OPTS[@]} $environment
NTest getApis ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getApi ${OPTS[@]} $host_alias $apiproxy $revision 2>&1 | tee -a $OUTFile
NTest getApiVersions ${OPTS[@]} $host_alias $apiproxy 2>&1 | tee -a $OUTFile
NTest getApiProducts ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getApiProduct ${OPTS[@]} $host_alias $apiproduct 2>&1 | tee -a $OUTFile
NTest getAppNames ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getApps ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getApp ${OPTS[@]} $host_alias $app_name 2>&1 | tee -a $OUTFile
NTest getCaches ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getCache ${OPTS[@]} $environment $cache_name 2>&1 | tee -a $OUTFile
NTest getCredentials ${OPTS[@]} $host_alias $app_name 2>&1 | tee -a $OUTFile
NTest getCredential ${OPTS[@]} $host_alias $app_name $consumer_key 2>&1 | tee -a $OUTFile
NTest getDeployedApiVersion ${OPTS[@]} $environment $apiproxy 2>&1 | tee -a $OUTFile
NTest getDevelopers ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getEnvironmentServers ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getEnvironments ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getEnvSrvrUuid ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getHost ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getHostUrl ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getKeystores ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getKeystore ${OPTS[@]} $environment $keystore_name 2>&1 | tee -a $OUTFile
NTest getLatestApiVersion ${OPTS[@]} $host_alias $apiproxy 2>&1 | tee -a $OUTFile
NTest getOrganization ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getProxFmProd ${OPTS[@]} $host_alias $apiproduct 2>&1 | tee -a $OUTFile
NTest getSvrNames ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getServers ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest getSrvrFmUuid ${OPTS[@]} $environment $server_uuid 2>&1 | tee -a $OUTFile
NTest getVirtualHosts ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest getVirtualHost ${OPTS[@]} $environment $virtual_host_name 2>&1 | tee -a $OUTFile

echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
echo -e "\t\tEnd of Testing $testName" 2>&1 | tee -a $OUTFile
echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
