#!/bin/bash

USAGE="environment"
TOOLSDIR="${APITOOLS_HOME}"

. "$TOOLSDIR/config/global"
. "$TOOLSDIR/lib/functions"
. "$TOOLSDIR/lib/nintestfunctions"

testName="$(basename $0)"
if [ "$OUTFile" = "" ] ; then
	OUTFile="${testName}.1.out"
	echo > $OUTFile
fi

parseCommandline "$@"
checkArgs 1
loadTestParams "${ARGS[0]}"
echo -e "\TNow Testing: $testName; OPTS=${OPTS[@]}; ARGS=${ARGS[@]}; OUTFile=$OUTFile; \n\t\ttestParams=$testParams" | tee -a $OUTFile

# re-parse using test Parameters
parseCommandline ${OPTS[@]} $testParams

loadConfig "${ARGS[0]}"
loadTestConfig 

NTest listAppNames ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest listApis ${OPTS[@]} $host_alias 2>&1 | tee -a $OUTFile
NTest listApiVersions ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile
NTest listStaleApis ${OPTS[@]} $environment 2>&1 | tee -a $OUTFile

echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
echo -e "\t\tEnd of Testing $testName" 2>&1 | tee -a $OUTFile
echo -e "\n\n\n\n" 2>&1 | tee -a $OUTFile
